name: ML Metrics Python Unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Labs/Github_Labs/Lab1/requirements.txt

    - name: Run ML Metrics Unittests
      run: |
        cd Labs/Github_Labs/Lab1
        python -m unittest test.test_unittest -v

    - name: Notify on success
      if: success()
      run: echo "✅ ML Metrics unit tests passed successfully!"

    - name: Notify on failure
      if: failure()
      run: echo "❌ ML Metrics unit tests failed!"