name: ML Metrics Testing with Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Labs/Github_Labs/Lab1/requirements.txt

    - name: Run ML Metrics Pytest Tests
      run: |
        cd Labs/Github_Labs/Lab1
        pytest test/test_pytest.py --junitxml=pytest-report.xml -v
      continue-on-error: false

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-test-results
        path: Labs/Github_Labs/Lab1/pytest-report.xml

    - name: Notify on Success
      if: success()
      run: echo "✅ ML Metrics pytest tests passed successfully!"

    - name: Notify on Failure
      if: failure()
      run: echo "❌ ML Metrics pytest tests failed!"