name: Pytest Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install pytest
      run: pip install pytest
    
    - name: Run tests
      run: |
        cd Labs/Github_Labs/Lab1
        pytest test/test_pytest.py -v