name: Unittest Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Run tests
      run: |
        cd Labs/Github_Labs/Lab1
        python -m unittest test.test_unittest -v